In [1]:
import numpy as np

arr = np.array([[0, 1, 2], [3, 4, 5]], 
              dtype=np.float32)
print(repr(arr))

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)


In [2]:
arr = np.array([0, 0.1, 2])
print(repr(arr))

array([0. , 0.1, 2. ])


In [3]:
a = np.array([0, 1])
b = np.array([9, 8])
c = a
print('Array a: {}'.format(repr(a)))
c[0] = 5
print('Array a: {}'.format(repr(a)))

d = b.copy()
d[0] = 6
print('Array b: {}'.format(repr(b)))

Array a: array([0, 1])
Array a: array([5, 1])
Array b: array([9, 8])


In [5]:
arr = np.array([0, 1, 2])
print(arr.dtype)
arr = arr.astype(np.float32)
print(arr.dtype)

int64
float32


In [9]:
arr = np.arange(5)
print(repr(arr))
arr = np.arange(5.1)
print(repr(arr))

array([0, 1, 2, 3, 4])
array([0., 1., 2., 3., 4., 5.])


Problem Statement #
Implement a function which removes all the even elements from a given list. Name it removeEven(list).

Input #
A list with random integers.

Output #
A list with only odd integers

Sample Input #
myList = [1,2,4,5,10,6,3]
Sample Output #
myList = [1,5,3]


In [10]:
myList = [1,2,4,5,10,6,3]

In [18]:
def removeEven(List):
    return [num for num in List if num % 2 != 0]

print(removeEven([3, 2, 41, 3, 34]))

[3, 41, 3]


In [17]:
def removeEven(List):
    odds = []
    
    for number in List: 
        if number % 2 != 0:
            odds.append(number)
    return odds

print(removeEven([3, 2, 41, 3, 34]))

[3, 41, 3]


In [1]:
def merge_lists(lst1, lst2):
    ind1 = 0
    ind2 = 0
    while(ind1 < len(lst1) and ind2 < len(lst2)):
        if(lst1[ind1] > lst2[ind2]):
            lst1.insert(ind1, lst2[ind2])
            ind1 += 1
            ind2 += 1
        else:
            ind1 += 1

    if(ind2 < len(lst2)):
        lst1.extend(lst2[ind2:])
    return lst1

In [2]:
def findSum(lst, value):
    foundValues = set()
    for ele in lst:
        if value - ele in foundValues:
            return [value-ele, ele]
        foundValues.add(ele)
    return False


print(findSum([1, 2, 3, 4], 6))

[2, 4]


In [3]:
def findSum(lst, value):
    # iterate lst with i
    for i in range(len(lst)):
        # iterate lst with j
        for j in range(len(lst)):
            # if sum of two iterators is value
            # and i is not equal to j
            # then we have our answer
            if(lst[i]+lst[j] is value and i is not j):
                return [lst[i], lst[j]]


print(findSum([1, 2, 3, 4], 5))

[1, 4]


In [4]:
def findSum(lst, value):
    for i in range(len(lst)):
        
        for j in range(len(lst)):
            
            if(lst[i]+lst[j] is value and i is not j):
                return [lst[i], lst[j]]
            
print(findSum([1, 2, 3, 4], 6))

[2, 4]
